### ISSUE TITLE
Quick user creation

### ISSUE THREAD

**Issue by albertogarciag95** [miw-upm/betca-tpv-angular#114]
- Create user minimum model
- Create user service call to post user
- Associate mobile to the ticket

Time estimated: 1h

**Comment by albertogarciag95** [comment]
Real time: 1h

**Comment by miw-upm** [comment]
El merge 21/03/2019 21:14 es incorrecto. Debes seguir la metodología vista en clase. Tal vez no tenias actualizado develop local respecto al origin
