### ISSUE TITLE
UI for Advanced Ticket Query

### ISSUE THREAD

**Issue by jliriano** [miw-upm/betca-tpv-angular#149]
First form for Advanced Ticket Query using:
* Client Mobile Number
* Date range
* Total range
* Pending (Pendiente de Entrega)

Second form for Advanced Ticket Query by Order Id using:
* Order Id
* Pending (Pendiente de Entrega)

Initial UI Interface: https://camo.githubusercontent.com/23f3ed9d7245bb6a689c756c86026c8e69be7747/68747470733a2f2f692e696d6775722e636f6d2f374b30654b39492e706e67

**Time estimate:** 5 hours
**Real time spent:** 6 hours

**Comment by miw-upm** [comment]
El merge entre origin/develop y develop debe realizarse con avance rápido (FF). 27/03/2019 13:45

**Comment by jliriano** [comment]
> El merge entre origin/develop y develop debe realizarse con avance rápido (FF). 27/03/2019 13:45

Por alguna razón mi IDE está forzando todos los merge entre origin/develop y develop local. Los comentarios automáticos que salen en los commit de merge no fueron utilizando --no-ff, solamente un git pull origin develop.
