### ISSUE TITLE
Show all orders

### ISSUE THREAD

**Issue by fatandazdba** [miw-upm/betca-tpv-angular#159]
We will see all orders. 
Estimated time: 2 hours

**Comment by fatandazdba** [comment]
Real time: 2 hours

**Comment by miw-upm** [comment]
El merge entre origin/develop y develop debe realizarse con avance rápido (FF). 27/03/2019 13:58

**Comment by miw-upm** [comment]
El merge se debe realizar entre ramas locales. Es incorrecto el merge 27/03/2019 13:39
