### ISSUE TITLE
Add update ticket

### ISSUE THREAD

**Issue by alvaroboni77** [miw-upm/betca-tpv-angular#189]

**Comment by miw-upm** [comment]
No comprendo esta tarea, cerrada pero no incorporada a develop

**Comment by alvaroboni77** [comment]
Perdón, te lo comenté en la entrega del moodle. No está funcionando correctamente debido a que no conseguí cargar los datos del ticket en la tabla del carrito de compra. Por eso no la incorporé a develop y cerré el issue por no dejarlo abierto indefinidamente.
