### ISSUE TITLE
Operator Manager - RRHH Component

### ISSUE THREAD

**Issue by vpaniego** [miw-upm/betca-tpv-angular#22]
Usar el `AppComponent` para crear el componente rrhh.
- [x] Prepara dummy para simular la consulta y carga de la tabla
- [x] Implementar dummy service para consultar el API Rest
Tiempo estimado: 7 H

**Comment by vpaniego** [comment]
Tiempo real empleado 10 H

**Comment by miw-upm** [comment]
El commit 17/03/2019 es incorrecto. Los merge deben realizarse con ramas locales
