### ISSUE TITLE
#30 Add staff component

### ISSUE THREAD

**Issue by hyl2099** [miw-upm/betca-tpv-angular#30]
#30 Add staff component

**Comment by miw-upm** [comment]
Buenas, has dejado roto desarrollo, no has puesto en el messaje del comit " #30" y los points no se pueden cambiar, porque es una estimación realizada ha priori. Los merge de los issue solo se realizan con develop local, por que que se deben actualizar las ramas develop primero. La aplicación NO arranca en local ahora

**Comment by miw-upm** [comment]
Buenas, has vuelto a romper develop... lo voy a arreglar de nuevo, pero te aconsejo que repases el manejo del flujo de trabajo antes de continuar.

**Comment by miw-upm** [comment]
El error parece que no has incluido la carpeta staff en el commit.
