### ISSUE TITLE
**Voucher apply**

### ISSUE THREAD

**Issue by ropili19** [miw-upm/betca-tpv-angular#32]
Create dialog voucher apply in windows purchase.

  

> Estimated: 2h
> Used: 3h
>

**Comment by miw-upm** [comment]
El commit y merge realizados el 12/03/2019, a las  21:20 y 21:56, son incorrectos.
Procura asegurarte de tener la rama develop sincronizada con origin/develop antes de cambiar nada de la aplicación

**Comment by miw-upm** [comment]
Y recuerda que la rama master no se puede utilizar nunca
