### ISSUE TITLE
Cash Movements - Create dialog

### ISSUE THREAD

**Issue by dpb-upm** [miw-upm/betca-tpv-angular#33]
- [x] Create dialog
- [x] Add links where is needed the dialog

> Estimated: 2h

**Comment by miw-upm** [comment]
Se deben realizar los Merge del issue# con develop con la opción --no-ff (Not Fast Forward)

**Comment by dpb-upm** [comment]
Disculpa. Me di cuenta despues de hacerlo, deje un comentario a través del chat de moodle.
