### ISSUE TITLE
Create Articles component

### ISSUE THREAD

**Issue by alexdelpuerto** [miw-upm/betca-tpv-angular#34]
- Create articles component
- Add component to Routing Menu >Products >Articles

**Comment by jolomoreno** [comment]
Hola! Te escribo por aquí ya que veo que Travis no me ha pasado la compilación y veo que el error ya estaba de tu subida. A ver si pudieras echarle un ojo. Gracias!

**Comment by miw-upm** [comment]
Cuando se actualiza develop respecto a origin/develop, SI se debe realizar avance rápido, es decir,
NO se debe utilizar --no-ff

**Comment by alexdelpuerto** [comment]
Lo estaba revisando el error pero no lo veo claro, al actualizar develop respecto del origin/develop yo hice pull

**Comment by jolomoreno** [comment]
Hola de nuevo, el error lo está dando cuando pasa los tests y, concretamente, en el archivo articles.component.spec.ts, ya que en el proyecto de Angular no hacen falta tests supongo que con eliminar ese archivo ya pasa Travis

**Comment by alexdelpuerto** [comment]
Resuelto por fin

**Comment by miw-upm** [comment]
Lo primero de todo es realizar fetch --all y comprobar que develop esta actualizado respecto origin/develop

**Comment by miw-upm** [comment]
Todos los commits deben llevar la referencia #xx
