### ISSUE TITLE
Create view to show articles

### ISSUE THREAD

**Issue by AngelicaGuaman** [miw-upm/betca-tpv-angular#36]
Show all articles

- [x] add article component

- [x] add routing

> Estimated: 2h

**Comment by AngelicaGuaman** [comment]
> Real time: 3h

**Comment by miw-upm** [comment]
Acuérdate para la próxima vez, antes de incorporar los cambios a develop, realizar un fetch y comprobar si develop esta sincronizado con origin/develop
