### ISSUE TITLE
Statistics - Create statistics display component

### ISSUE THREAD

**Issue by tomas-teston** [miw-upm/betca-tpv-angular#38]
Crear un componente que ejerza de panel de administración de estadísticas donde se podrá seleccionar el intervalo de fechas por el que se quiere realizar la estadística y la estadística que queremos visualizar. Existirá un botón "buscar" y realizará una petición a BE desde el servicio de API, recogerá los datos y mostrará una gráfica en la parte inferior. Las gráficas disponibles podrán ser:
Ventas totales por día en un periodo de tiempo.
Media de gasto diario en un periodo de tiempo.

> Tiempo estimado: 6h

**Comment by miw-upm** [comment]
El commit 43482b82, 11/03/2019 14:59 resulta redundante, ya que justo antes, en el commit 0f9568f1, se tiene la rama develop & origin/develop en el mismo commit, y por lo tanto ya estaba actualizado

**Comment by tomas-teston** [comment]
Cierto, ese Commit sobraría. Gracias!

**Comment by tomas-teston** [comment]
Time: 4h
