### ISSUE TITLE
Create update roles dialog

### ISSUE THREAD

**Issue by AlexandraCabreraLituma** [miw-upm/betca-tpv-angular#45]

**Comment by AlexandraCabreraLituma** [comment]
Tiempo Estimado: 2 horas 
Tiempo Real: 1 hora

**Comment by albertogarciag95** [comment]
Hola Alexandra,

Te escribo para comentarte que tengo que realizar un pequeño cambio en la apertura de tú diálogo de update roles. Necesito mostrar desde Users Management un diálogo de creación/edición del usuario. He visto que el botón + de creación y el de editar, redirigen al dialogo de roles. 

Lo que haré en mi issue será crearte un botón en el dialogo de editar usuario, para que desde aquí se habrá tú dialogo de roles. Y el botón + debe redirigir al diálogo de crear usuario así que lo cambiaré también. Cualquier cosa que no te cuadre no dudes en comentarme.

Gracias!
Un saludo

**Comment by AlexandraCabreraLituma** [comment]
Hola alberto 

Gracias por comentarme, lo he colocado temporalmente en el botón de + de creación debido a que no he visto a un desarrollador  asignado en la wiki para User. 

Un saludo
