### ISSUE TITLE
Add Sendings Service and Create CreationDialog

### ISSUE THREAD

**Issue by L-Xinyu** [miw-upm/betca-tpv-angular#52]
Add Sendings Service and Create CreationDialog

**Comment by miw-upm** [comment]
En los mensajes de los commit debes poner " #52".
Has creado un test erróneo que rompe la rama de desarrollo

**Comment by miw-upm** [comment]
En los mensajes de los commit debes poner " #52".
Has creado un test erróneo que rompe la rama de desarrollo

**Comment by miw-upm** [comment]
Antes de trabajar con un issue#, debes moverlo a la columna de  "In progress"
