### ISSUE TITLE
Offers - Add Offers (no Articles List hardcore data)

### ISSUE THREAD

**Issue by jolomoreno** [miw-upm/betca-tpv-angular#84]
Description: Create Offer adding Articles to ArticlesLine in Offer checking if exists in List of Articles Id.

- [x] Add **Article** (hardcore data) to **Articles List** (without check if **Article Id**  exists in list of **Articles Id** mock)
- [x] Create Add **Article** reactive form and get his data.
- [x] Add **Article** to **Articles List**  searching **Article Id** using call to API /articles/{idArticle}
- [x] Create **Offer** using **Offer Service** (without API connection).

> Estimated: 5h

**Comment by jolomoreno** [comment]
> Real Time: 4h

**Comment by miw-upm** [comment]
El commit 19/03/2019 23:53 es incorrecto. Se debe trabajar con ramas locales

**Comment by jolomoreno** [comment]
Creo que ocurrió porque utilicé la opción "No ff " en el momento de hacer el merge de develop con mi rama local (issue#84) y (a la vez) se hizo un pull de la rama origin/issue#84. Lo tengo en cuenta para los siguientes commits y merges. Muchas gracias por la corrección @miw-upm
